{{- if and .Values.persistence.enabled .Values.persistence.useStaticLocalPV }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "hellonginx.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""                     # must be empty to match the PVC below
  volumeMode: Filesystem
  local:
    path: {{ .Values.persistence.hostPath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - {{ .Values.persistence.nodeName }}
{{- end }}

